[versions]
agp = "8.11.2"
junit = "1.3.0"
kotlin = "2.2.21"
compileSdk = "36"
minSdk = "24"
composeBom = "2025.11.00"
appcompat = "1.7.1"
material = "1.13.0"
activityCompose = "1.11.0"
recyclerview = "1.4.0"
benchmark = "1.4.1"
runner = "1.7.0"
uiautomator = "2.3.0"
profileinstaller = "1.4.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark" }
benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "benchmark" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }