[versions]
agp = "8.6.1"
kotlin = "2.0.0"
compileSdk = "35"
minSdk = "24"
composeBom = "2025.01.00"
appcompat = "1.7.0"
material = "1.12.0"
activityCompose = "1.9.3"
recyclerview = "1.3.2"
constraintlayout = "2.2.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-constraint = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }